version: 2
jobs:
  build:
    docker:
      - image: node:latest
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /gitbook
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: /gitbook
          paths:
            - .
  deploy:
    docker:
      - image: node:latest
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /gitbook
    steps:
      - attach_workspace:
          at: /gitbook
      - add_ssh_keys
      - run:
          name: install
          command: npm install
      - run:
          name: ssh setting
          command: |
            touch ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: user setting
          command: |
            git config --global user.name  "CircleCI"
            git config --global user.email "circleci@gh-pages.com"
      - run:
          name: deploy
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
